name: Go
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: 1.23 }
      - run: go build -v ./...
      - run: go test -coverprofile=coverage.out ./...
      - uses: coverallsapp/github-action@v2
        with: { file: coverage.out, format: golang }
